spring.application.name=creative-lines

server.port=${SERVER_P0RT:8080}
server.address=${SERVER_ADDRESS:0.0.0.0}

# DATASOURCE
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5445/creative-lines}
spring.datasource.username=${DATASOURCE_USERNAME:root}
spring.datasource.password=${DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA PROPERTIES
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.hibernate.naming.implicit-strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
spring.jpa.properties.hibernate.show_sql=${HIBERNATE_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true